In [1]:
mylist = ["apple", "banana", "cherry"]

In [2]:
print(mylist)

['apple', 'banana', 'cherry']


In [3]:
print(type(mylist))

<class 'list'>


In [6]:
import numpy as np
myarray = np.array(["apple", "banana", "cherry"])

In [74]:
print(myarray)
print(myarray.ndim)

['apple' 'banana' 'cherry']
1


In [8]:
print(type(myarray))

<class 'numpy.ndarray'>


In [12]:
convertlist=np.asarray(mylist)
convertlist

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [13]:
print(type(convertlist))

<class 'numpy.ndarray'>


In [20]:
zeros_array = np.zeros((5, 2))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
transpose = zeros_array.T
transpose

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
a = np.arange(10).reshape((5, 2))
arange

array([[0, 1],
       [2, 3],
       [4, 5]])

In [51]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [52]:
reshape_array = arr.reshape(4, 3)
print(reshape_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [55]:
array1 = np.array([[99, 12], [36, 43]])
array2= np.array([[5, 6]])
np.concatenate((array1, array2), axis=0)

array([[99, 12],
       [36, 43],
       [ 5,  6]])

In [56]:
np.concatenate((array1, array2.T), axis=1)

array([[99, 12,  5],
       [36, 43,  6]])

In [69]:
x = np.arange(1.0,16.0)
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [70]:
np.split(x, 3)

[array([1., 2., 3., 4., 5.]),
 array([ 6.,  7.,  8.,  9., 10.]),
 array([11., 12., 13., 14., 15.])]

In [72]:
a_split=np.arange(8.0)
np.array_split(a_split, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [75]:
array=np.array([[0,1],[2,3]])
array

array([[0, 1],
       [2, 3]])

In [77]:
np.resize(array,(2,3))

array([[0, 1, 2],
       [3, 0, 1]])

In [78]:
np.resize(array,(1,4))

array([[0, 1, 2, 3]])

In [87]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
np.delete(arr, 0,0)

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
np.delete(arr, 0, 1)

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])